### ISSUE TITLE
Cicero: post reditum ad quirites, cum populo gratia egit, post reditum ad populum

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#220]
in Cicero, go to Oratoria works. we listed  "Post reditum ad quirites", however when the book is selected, the title is "Post reditum ad populum - Cicero"  
also, when I go back to Works, the book title is "Cum populo gratia egit"
Not sure if there is a specific reason for using a different title for the same work. or if there was a good reason, I can't remember.

see screenshot

![cicero-works](https://user-images.githubusercontent.com/41396793/61313861-52be9e80-a7c9-11e9-9e32-e24376485046.JPG)

![cum populo-cicero](https://user-images.githubusercontent.com/41396793/61313889-64a04180-a7c9-11e9-9d19-0a789fc223d3.JPG)

**Comment by monzug** [comment]
I also noted that we use "in Verrem" and "in C. Verrem"

**Comment by balmas** [comment]
no good reason for these differences, just discrepancies in metadata. Will fix.

**Comment by balmas** [comment]
it's actually related to #40 which I had marked as won't fix. I won't touch this code right now but I can get rid of the multiple conflicting titles in the data.

**Comment by monzug** [comment]
others in Cicero, De lege agrarian contra Rullum (orations de lege agrarian) , pro lege manilia (de imperio contra pompei)

**Comment by balmas** [comment]
should be fixed for all Cicero titles now.

**Comment by monzug** [comment]
Thanks for fixing the reported issues above. while checking all Cicero work, I noticed that we still have some minor discrepancies, mainly in table of contents. I think we can leave with this for now.
1) de lege agrarian contra rullum: we still have an instance where the title is Orationes de Lege Agraria  (table of contents) - see screenshot
![cicero-delegeagraria](https://user-images.githubusercontent.com/41396793/61639861-4a9fac80-ac6a-11e9-8a65-b78ec4aae559.JPG)
2) In Caecilium: we have in Caecilium (in Works), in Caeciliu, and Divinatio in Q. Caecilium (in TOC)
3) in Verrem: in C. Verrem in TOC
4) Post reditum ad populum: Post reditum ad quirites in TOC
5) Pro Roscio comoedo: Pro Q. Roscio comoedo in TOC
6) Pro Tullius: for Marcus Tullius  on top nav     ----->    this is the only that I would update right now. @balmas?
7) Pro lege manilia: De imperio Cn. Pompei in TOC

**Comment by balmas** [comment]
most of these were caching problems -- I forgot to clear the cache after deploying. The exception where these two, which I will fix:

Pro Tullius: for Marcus Tullius on top nav 

and 

Caecilium: we have in Caecilium (in Works), in Caeciliu

**Comment by balmas** [comment]
all should be fixed now.

**Comment by monzug** [comment]
yes.
